### ISSUE TITLE
updating @apollo/client breaks starterkit

### ISSUE THREAD

**Issue by adamsoffer** [TheRusskiy/next-apollo-ts#1]
Hey!@TheRusskiy! First off, this is awesome! Would love to see this example featured as the "official" apollo example at some point.

Heads up I'm running this with the latest version of `@apollo/client` and I noticed it throws an error due to the deprecated helper `FieldValueToBeMerged` used [here](https://github.com/TheRusskiy/next-apollo-ts/blob/master/utils/reconcileProcessedFields.ts#L5).

It was removed from apollo in [this commit](https://github.com/apollographql/apollo-client/commit/8172159e7033d195b5dd7747ecb54c8b437a0df9).

**Comment by TheRusskiy** [comment]
@adamsoffer thanks for pointing that out!
I had a feeling this feature is highly dependent on apollo client implementation,
the easiest thing to do is to remove this block of code:
https://github.com/TheRusskiy/next-apollo-ts/blob/4f2ae141b11f618c0f4055abeb460241746ff4c5/components/withApollo/index.tsx#L134-L146
Until I have a chance to look at the current Apollo implementation of merging state.
By removing it, the app is going to make requests when you navigate from one page to another that was statically generated, instead of reusing apollo state from that page. This is how the "official" example working, so no big deal I suppose, still want to fix this though.

**Comment by TheRusskiy** [comment]
@adamsoffer 
Based on updated apollo code it looks like we can just replace
```typescript
   const merger = new DeepMerger(reconcileProcessedFields) 
   client.cache.restore(merger.merge(apolloState, client.cache.extract())) 
```
with simply
```typescript
   const merger = new DeepMerger() 
   client.cache.restore(merger.merge(apolloState, client.cache.extract())) 
```
And scrap the whole `reconcileProcessedFields` function.
It's going to use a default "reconciler": https://github.com/apollographql/apollo-client/blob/d96f4578f89b933c281bb775a39503f6cdb59ee8/src/utilities/common/mergeDeep.ts#L61-L98
That's what they are doing now: https://github.com/apollographql/apollo-client/blob/29d41eb590157777f8a65554698fcef4d757a691/src/cache/inmemory/helpers.ts#L68-L70
I haven't tried it yet though.

**Comment by TheRusskiy** [comment]
Updated the repo: 
https://github.com/TheRusskiy/next-apollo-ts/commit/6a7ae017d4a4f21e492f2cd609bb004c9eecb053
Also had to change `'@apollo/react-ssr'` to `'@apollo/client/react/ssr'` because the former stopped working with the new apollo client version

**Comment by adamsoffer** [comment]
ah thanks! 

>By removing it, the app is going to make requests when you navigate from one page to another that was statically generated, instead of reusing apollo state from that page. This is how the "official" example working, so no big deal I suppose, still want to fix this though.

I noticed in dev mode my app makes a request when I navigate to a page that was already statically generated and isn't reusing apollo state. I'm guessing this is why?

**Comment by TheRusskiy** [comment]
@adamsoffer  unfortunately, the only way to test this functionality is "build" the app, in development  mode it doesn't precompile pages.
Also, to be clear, I advise applying changes from my last commit to this repo, the latest client version wasn't playing nice with apollo/react-ssr.

**Comment by adamsoffer** [comment]
> unfortunately, the only way to test this functionality is "build" the app, in development mode it doesn't precompile pages.

Gotcha. I thought once you visit a page, apollo caches its data so that subsequent visits are instantaneous. But I guess that's not the case with getStaticProps.

> Also, to be clear, I advise applying changes from my last commit to this repo, the latest client version wasn't playing nice with apollo/react-ssr.

Thanks, yeah update apollo to the latest version and made your suggested changes and the error went away 👍
